### ISSUE TITLE
共用コンポーネントの作成

### ISSUE THREAD

**Issue by MATCHAo2** [INIAD-FES-2022/venue-frontend#4]
すべてのページで一貫して表示される部品の作成
最低限の物を用意
feature/common のブランチで作業すること

**Comment by MATCHAo2** [comment]
ブランチをcommonに変更
Terminal部分はcommon/terminalで

**Comment by littleswampman** [comment]
Terminal部分はほぼほぼ完成しました

**Comment by littleswampman** [comment]
現時点では他に用意する必要がある共用コンポーネントは無いと思うので一旦クローズします
